exports.up = (knex) => knex.schema.createTable('products', (t) => {
  t.uuid('id').primary().defaultTo(knex.raw('gen_random_uuid()'));
  t.string('title', 300).notNullable();
  t.string('slug', 350).notNullable().unique();
  t.text('description');
  t.text('short_description');
  t.decimal('price', 10, 2).notNullable();
  t.decimal('original_price', 10, 2);
  t.decimal('discount', 5, 2).defaultTo(0);
  t.string('currency', 10).defaultTo('INR');
  t.uuid('category_id').references('id').inTable('categories').onDelete('SET NULL');
  t.string('brand', 100);
  t.uuid('merchant_id').references('id').inTable('merchants').onDelete('SET NULL');
  t.string('affiliate_url', 1000);
  t.decimal('rating', 3, 2).defaultTo(0);
  t.integer('review_count').defaultTo(0);
  t.boolean('featured').defaultTo(false);
  t.boolean('trending').defaultTo(false);
  t.enum('status', ['draft', 'published', 'archived']).defaultTo('draft');
  t.string('sku', 100);
  t.enum('availability', ['in_stock', 'out_of_stock', 'limited']).defaultTo('in_stock');
  t.jsonb('specifications');
  t.string('meta_title', 200);
  t.text('meta_description');
  t.string('canonical_url', 500);
  t.timestamps(true, true);
  t.index(['status', 'featured']);
  t.index(['status', 'trending']);
  t.index(['category_id']);
  t.index(['merchant_id']);
});
exports.down = (knex) => knex.schema.dropTable('products');
