import api from './index';
export const getDashboard = () => api.get('/admin/dashboard');
export const getAnalytics = (params) => api.get('/admin/analytics', { params });
export const getUsers = (params) => api.get('/admin/users', { params });
export const updateUser = (id, data) => api.patch(`/admin/users/${id}`, data);
export const getBanners = () => api.get('/admin/banners');
export const createBanner = (data) => api.post('/admin/banners', data);
export const updateBanner = (id, data) => api.patch(`/admin/banners/${id}`, data);
export const deleteBanner = (id) => api.delete(`/admin/banners/${id}`);
export const getDeals = () => api.get('/admin/deals');
export const createDeal = (data) => api.post('/admin/deals', data);
export const updateDeal = (id, data) => api.patch(`/admin/deals/${id}`, data);
export const deleteDeal = (id) => api.delete(`/admin/deals/${id}`);
export const getSettings = () => api.get('/admin/settings');
export const updateSettings = (data) => api.patch('/admin/settings', data);
